### ISSUE TITLE
Funnel tracking 

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#122]
Figure out best way to track this funnel (mixpanel?)
- [ ] user clicks the email link
- [ ] Goes to homepage
- [ ] Sets up password
- [ ] Clicks request guru page
- [ ] Enters course
- [ ] Requests help
