### ISSUE TITLE
[UX Content Enhancements] Text/Content that is important to change, but not necessary.

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#208]
A lot of UX Workflows need to be more clear and are separate issues. I'm combining them into one where I just focus on it, and create issues once I've solved it. A lot of these things might be eliminated completely, so i'm just keeping track here.

@dustyknapp , a lot of these are your issues. Fortunately, you're going to help solve them :P 
- [ ] Tutor billing student after the session #59 
- [ ] Clarify Packages text (we might remove them completely). #47 
- [ ] Greenbox on landing page needs to be removed. #43
- [ ] Change "credit" to "credits earned" on referral code page #42
- [ ] "Click here to see deals" should be "Save up to $200 .. #8 
- [ ] Not clear to student that they should select Econ 100B, or Econonmics 100B #6 
- [ ] Contacted Gurus should have some text clarifying that these Gurus are not available yet. #125 
- [ ] Confirmation for tutors not getting updated #118 
- [ ] Create content for referral code page #41 
- [ ] Change or remove "Give $5, Get $5" from homepage #35
