### ISSUE TITLE
Engineering Plan

### ISSUE THREAD

**Issue by choochootrain** [u-guru/uguru#3826]
Here is a super-issue of changes that I think we should implement. Sub-issues will be distributed out
- [ ] Spin up a staging platform for testing large changes (SSL, migrating to AWS, schema migrations, etc)
  - [x] Set up staging.uguru.me domain and uguru-staging dyno heroku app
  - [ ] Add Flask middleware to password protect the staging instance (#3827)
  - [ ] Evaluate migration to AWS?
- [x] Set up HTTPS
  - [x] Provision SSL endpoint on staging.uguru.me and work out all bugs serving assets
  - [x] Schedule time to migrate production server and domain to HTTPS
- [ ] Security auditing
  - [ ] Check authentication flow for any leaked information (#3828)
  - [ ] SQL injections via SQL Alchemy (#3829)
  - [ ] Verify payment info is secure end-to-end (#3830)
- [ ] Database auditing
  - [ ] Optimize expensive queries for the current workload (#3831)
- [ ] Code auditing
  - [ ] Remove API keys from commit history (#3832)
  - [ ] Check request limits for Mailgun, Twilio, other services (#3833)
  - [ ] Flask series testing
  - [ ] Audit janky parts of the code
- [ ] Infrastructure
  - [ ] Update README to match current install and deployment steps (#3834)
  - [ ] Add flake8 and jshint to pre-commit hook for style checking (#3835)
  - [ ] Fix spammy error emailer
    - rate-limit emails if the message is the same each time
    - use env variables to suppress all error emails if not on production server
    - discard invalid issues opened by tracebacks
      - this will take a while but is pretty important for task management
- [ ] Engineering
  - [ ] Code reviews
    - or at the very least, 2 people should know every part of the code
  - [ ] Task and issue management
  - [ ] Testing
    - Integrate tests with CircleCI - tests take 5 extra minutes to write but can save you hours
- [ ] Performance Testing
  - [ ] Server benchmarking
    - What is the maximum sustained load 1 dyno can handle?
    - How does it scale with the number of dynos?
    - What is the best plan for scaling out as load increases?
      - What is the cost for this?
