### ISSUE TITLE
v0.1 Setup Guru Profile Master Issue Tracker

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#3858]
#### CSS-Related
- [x] Move add buttons to edit mode on student profile and add filler
- [x] Add Uguru text on the access page
- [ ] First iteration of student home (no animations on map yet)
  - [x] Find a good google maps svg && approve with Samir & discuss functional requirements to be productive
  - [ ] Add markers on the map that look good school customized
  - [x] Add overlay, request help, become a guru button
  - [ ] Discuss request form precursors. What you proposed earlier works but let's finalize a version since there are UX experiments on the agenda.
  - [ ] Finish this based on discussion
- [x] Home page bottom icons
  - [x] {Center}Add your courses (replaces become a guru)
  - [x] {left}Home one (We can keep same but icon needs to be styled)
  - [x] {Right}  Settings Icon
- [ ] Guru Ranking Tour Guru
  - Set startpage to '^.guru'
  - Uncomment the section at the bottom that says '_GABRIELLE_' on the bottom of guru.ctrl.js
  - Edit 'guru.ranking.popup.html'
- [x] Double spin on the swap guru / swap student mode @nicknaky @elletricity is this intended? 
- [ ] IE specific CSS (Whoever gets to it first))
#### Data Related
- [ ] Get Data of all of the following @Ben095 
  - [x] Wyzant
  - [x] uLoop
  - [x] University tutors.com
  - [x] cardinaltutors
  - [ ] Cheggtutors.com
- [ ] Sanitize data so we have 50 "data-complete" universities @Ben095 
- [ ] Write scripts to auto-update targetted universities on website if it meets certain requirements
#### Performance Related

_If it's "notice-able" then it should be here & prioritized based on 1. How noticeable && 2. Distance to the first time experience for the user_
- [ ] Make a list of all edge-case nightmares & determine whether it will impact more than 10% of 1000 users (across all platforms). Add other things if you would like to this one @nicknaky 
- [ ] Foundational for the following (we should be able to clearly track & filter these in analytics since they are categorized)
  - [ ] Download speed (+ do some background reading)
  - [ ] Modals --> one modal at a time
  - [ ] Local assets
- [ ] Make android feel nice on first time download
  - **Side note:** We can push a new build anytime for android, only takes a couple of hours to do so
#### Content Related
- [ ] Polish the home page content
- [ ] Polish the app copy
#### Extra for experts

_These represent features that are rolled in the next release that could be kept within this one_
- [ ] Become a Guru: Add a Deposit
- [ ] Become a Guru: Referral link 
- [ ] Become a Guru: Methods of Communication
- [ ] Become a Guru: Experiences
- [ ] Push Notifications

@elletricity @nicknaky @Ben095 @elletricity
