### ISSUE TITLE
Gabrielle Tasks 10/7

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#3873]
### Resolve these bugs quickly
- [x] All list items need a touch state as well (not just buttons && links). Example --> when you tap a guru experience (to edit it)
- [ ] Show the #of years visually around slider. Right now the user cannot see / tell the value they have selected You can template it real time by making the text-value within the HTML brackets "{{experience.years}}" or set the slider ng-value="experience.years"
- [x] The toast/notification needs a call to action button. Something visible where the user knows that if they tap it, it will do something.
- [x] Loader text formatting. If you call $scope.loader.showSuccess("Hey....", 1000000), it will show the loader for 1000000 ms --> in case you wanted to edit it without it disappearing. 
### Tasks for today
1. Bugs (above)
2. Animation gameplan --> how to make this iteration more fluid & feel natural
   _Before moving to step 3.. you will_
   - [ ] List of components to animation
   - [ ] Which velocity components you will animate
   - [ ] Discuss to the extent you feel comfortable that implementation is so easy it's a joke
3. Implement strategy/gameplan from number 2. Simple == key to success, let's avoid anything ambitious today. 
4. Finish #3 and you can work on guru / bakery after. 
### Later (next release)
- [ ] Contacting Modal
- [ ] Guru Web Profile Version
- [x] Jeselle's Photo && Bakery Guru
- [ ] Desktop Version
- [x] Guru introduction
- [ ] Guru Communications
- [ ] Style Guru Referral && Share
- [ ] Styling add/remove/update Credit card UI (will be implemented already)
