### ISSUE TITLE
Tasks 10/12/2015

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#3888]
## **Jeselle**

_@jeselleobina_
- [ ] All Tasks Explained in #3884 
## **Nick && Jason**

*@nicknaky @f230536 *
- [x]  Android Splashscreen #3885
- [x] Safari Incognito #3882 
- [x] Weird Digest error #3881
- [x] #3891
- [ ] [Jason] Write all manual tests for issues above for nick
- [ ] [Nick] Bash Scripts #3887 (Verification will be trying it on Samir's laptop)
## **Gabrielle**

_@elletricity_
- [x] Redeeem CSS #3886
- [x] #3879
- [ ] Resolve all critical bugs assigned to you first && label with plz verify after you push #3890 #3841
- [ ] Maintain circle && proper ratio CSS for guru profile image (&& acrosss all photos)
- [ ] Edit University option in sidebar before user signs in
- [ ] Methods of communication Guru Profile
- [ ] Show #of years around the year slider for experience
- [ ] university.background_url into the sidebar
- Earnings
  - [ ] _Discussion_ -- Add current balance to Guru home page
  - [ ] _Discussion_ -- Allow modification of hourly rate on guru profile
- [ ] Signup / Signin like referenced in #3879 (https://redpen.io/p/yzdba9799c3e894456)

**sam1rm** 
- [ ] Add Github production exceptions to the master build (LOCAL) for today
- [ ] Create toggle for logging exceptions in admin mode
- [ ] Clean all github issues 
- [ ] Remote production push bug
- [ ] Go through && filter #3876 
- [ ] Go through each major workflow && iterate on bugs && performance [MAJOR] 
- [ ] Android / iTunes Script
## **ben**

_@Ben095_
- [ ] Craigslist create a post 
- [ ] Twitter Wrapper 
- [ ] Monoprice -- buy a cable
- [ ] Mandrill Wrapper
- [ ] Stripe Wrapper 
- [ ] Learn how to display data 
## *\* IF TIME --- Nick / Samir**
- [ ]  Push Notifications service / refactor anything that has $cordovaPush or window.pushWhateverTheVariableIS
  -[ ]  Sharing --> prompts android intents + iOS intents/share options (not sure what the plugin is called but it exists)
- [ ]  Card.io
- [ ]  Bonus Apply Pay / android pay
