### ISSUE TITLE
10/13/2015

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#3912]
Morning Chores
- Instacart please order on iPad (everyone has up to $10 budget). Ping me if questions
- Expect to order office electronic-related equipment (extensions, etc) -- start thinking what u need

Daily Schedule (impt events)
_9-10am_: Samir + Jeselle BB room
_10am-11am_ Tech Meeting && Go over daily goals
**10:30am-11:00am** Project Euler Programming Competition
**11am - 1pm**  Samir needs to catchup on sleep DOB
**1pm - 1:30pm** Afternoon check-in / office hours / q&a if needed (optional)
## **[Jeselle](https://github.com/sam1rm/uguru/issues/assigned/jeselleobina)**

_@jeselleobina_
- [ ] All Tasks Explained in #3884 
## **[Nick](https://github.com/sam1rm/uguru/issues/assigned/nicknaky) && [Jason](https://github.com/sam1rm/uguru/issues/assigned/f230536)**

*@nicknaky @f230536 *
#### **Nick-only + Jason Verify**
#3904, #3918, #3914, #3908, #3903, #3893, #3892
#### **Nick-only Features to implement**

```
* for each of these 
```
- [ ] Card.io
- [ ] Cordova Social Auth
- [ ] Cordova Share (the social)
- [ ] Push Notifications w/ Samir (go over first)
#### **Jason-only**

_from yesterday_
**Do this first**
#3891 -- see comments + more

_today_
_Anything with "stress-test" --> you should *_immediately*\* file all bugs that you find related to it

**Do these from left to right** plz --> if you get stuck, move one to the right 
#3819, #3895, #3905, #3897, #3894, #3901 #3899
## **Gabrielle**

_@elletricity_
      - Earnings
     - [ ] _Discussion_ -- Add current balance to Guru home page
     - [ ] _Discussion_ -- Allow modification of hourly rate on guru profile
- [ ] Signup / Signin like referenced in #3879 (https://redpen.io/p/yzdba9799c3e894456)

**sam1rm** 
- [ ] Add Github production exceptions to the master build (LOCAL) for today
- [ ] Create toggle for logging exceptions in admin mode
- [ ] Clean all github issues 
- [ ] Remote production push bug
- [ ] Go through && filter #3876 
- [ ] Go through each major workflow && iterate on bugs && performance [MAJOR] 
- [ ] Android / iTunes Script
## **[Ben](https://github.com/sam1rm/uguru/issues?q=is%3Aopen+is%3Aissue+assignee%3ABen095+label%3ACritical)**

_@Ben095_
- [ ] Craigslist create a post (Finish plz)
- [ ] Monoprice -- buy a cable See more details here 
- [ ] Learn how to display data 
  - [ ] Upload hella data onto admin dashboard
## *\* IF TIME --- Nick / Samir**
- [ ]  Push Notifications service / refactor anything that has $cordovaPush or window.pushWhateverTheVariableIS
  -[ ]  Sharing --> prompts android intents + iOS intents/share options (not sure what the plugin is called but it exists)
- [ ]  Card.io
- [ ]  Bonus Apply Pay / android pay
