### ISSUE TITLE
Nick Todo 10/22

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#3961]
#### Continuance from yesterday (finish these first)
- [x] Setup [zenhub](https://github.com/uguru/uguru/wiki) & bare-minimum familiarize yourself
- [x] Export your plugins as a new repository within the _uguru_ ogranization. I've already provided your account access to do so. Let me know if its not working
- [x]  Significant progress on Jason's dev env setup
- [x]  Push notifications cross platform
- [ ]  Schedule show and tell (< 30m) after plugins have been
  1. Best implemented to your availability for the platforms they support
  2. There is some guide somewhere which will set it up on both mine & jason's if we follow if (add it to ug_build if it will take < 30 minutes --> totally worth it)
  3. They appear to work with live reload & jason has tested it
  4.  We go over the quirks for each one (so make sure you understand all the "fine print" that could fuck us later"
#### New plugins for the day
- [x] _FIRST_ Check out telerick && see if there is anything interesting that is one-time setup, long-term potential use-case && doesn't invite privacy.
- [ ] OAuth
- [x] Microphone / Media 
- [x] InAppGoogleMaps 
#### Other (eventually become regular like morning tasks)
- [ ] Time && refactor code for at 1 hour total
