### ISSUE TITLE
Nick 10/27

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#4035]
## Agenda
- Task #1 
- Task #2 
- Learn how to do this with github
  - Update from other peoples mobile-app/scripts but _never_ update from mine (one-way binding)
  - get a list of all active users in the past week on our remote branch uguru/uguru
  - get a list of one users comments, ordered by recent
## Task #1 Remote Data Service

_Fetching & storing at the right time & place_
1. - Read the spec below, meet, and ask any questions. No background threads, decrease risk. 
   - Spend 15 minutes researching, learning, building stronger base, or even propose execution method than below
   - For each bullet-point, add a "best-case" & "worst-case" time-bound in the comments. (i.e. 1-2pm best time, 1-3pm worst case)
   - Ping me to meet -- if you're 100% confident & then don't need to, that's fine! Let me know when you start. 
2. Modularize the service for the rest of the task
   - Fetch all remote data asynchronously when there is a _steady_ internet connection
   - If steady, use consecutive (back to back) timeouts
   - Think about the best naming, access methods, static variables (look it up to confirm) for this service. 
   - Create all empty functions necessary -- modularity, do not implement anything until you are done with the entire process. See below for list of requirements. What are the main steps/functional components to successfully execute?
     - [ ] Fetch data w/o impacting UI Thread
     - [ ] Store data based on platform
     - [ ] Dump/decrease data payload (size)
     - [ ] How to effectively communicate with other services that are in the same controller -- without it getting in the GUI? 
     - [ ] Failover case: what if we don't get the data in X seconds -- what if something happens where it has no idea when it's going to get the data?
   - Execute & apply to first the _courses_ controller
3. Rubric
   - Apply to courses (the hardest one)
   - &Requirements&
     1. Seamless transitions. Slider must be seamless from home --> major --> courses 
     2. GUI Thread should not be impacted at the slightest bit (aside from loaders for that particular screen)
     3. Efficient storing based on usability. How frequent will this dataset be used for the user?  Does it need to be local? What portions should be local? 
     4. Must be able to dispatch & receive events from other entities without GUI thread 
     5. Sensible modularity. (getting this right is _hard_)
        - University, Courses, and Majors should be passed into this service
        - Methods such as "fetchOnStart", "refetch", "notifyUser", "dispatchSuccessEvent" etc. All functionalities should be encapsulated with respective environments, no entity should not more than it has to, or know how to speak/communicate with other entities
     6. Bonus (only if you are around best case time intervals)
        - FetchOnControllerLoad
        - FetchBeforeStateTransitionMode
          - Look at events fired before state.go() transitions
4. Apply 
   - To the remainder controllers that have remote data. 
5. Track
   - Add analytics to this on localytics
   - Detect local vs production model (window.location.url is one way + look up other best way if you're still interested)
6. Cleanup, refactor, teach 
   - Go best practice
   - Schedule 10:30am tech-talk where you will go over this with the rest of the team
   - Schedule a tech-talk with everyone (5x5 slide)
   - don't spend more than 30m than this, very informal + you can even just pull out your code on stage
### Tast #2 List Views
1. Create a list of all the reasons why the list view is not as seamless as me  flicking my finger like that react app (reasonable to you). You can have different ones for different platforms. 
   - Remember -- be efficient
   - if you can pull an ionic repo with a list view that is seamless, why not just fork it, copy it & add our shit to it? 
2. Do research until you understand it -- ask me questions if need a stronger foundation with any concepts. Happy to white board anything. 
3. Schedule &  w/ me -- to make sure I don't add anything to the picture last second
4. Based on the one's we agree on the most -- try to apply that methodology 
### Tool setup / efficiency / etc

_Apply shoot-your-self-in-the-foot-terminology_
**Do these in order of impact, but of course, it's okay to indulge in something more exciting for a bit first**
Also, please add more to this as we go -- it's always good to keep someone on top of this on an ongoing basis. 
- [ ] [This one has to be first - click why](https://play.google.com/store/apps/details?id=me.autotouch.autotouch&hl=en) -- Once you find write workflow -- delegate jason to set itup
- [ ] Install sublime plugins that enforce best practices (Take note of the things you wish you had)
- [ ] How to best enforce javascript best style practices etc. 
- [ ] There are literally plugins that will not let you submit to github if you don't follow certain rules like "the comments must have full sentences. 
- [ ] .gitignore
