### ISSUE TITLE
Jason 10/27/2015

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#4037]
# Task 0:
- [x] Set a timer for 30 minutes
- [x] Read this https://pragprog.com/magazines/2012-01/unit-tests-are-first
- [x] Write a comment answer this
  
  ```
     1. Do you agree with the principles here? 
        - Yes.
     2. What do you need to do/understand
        - Self-Verifying
     3. Create a game-plan referencing the tools we use right now -- how we can follow these principles
       - Since the article is about unit test , we probably may need to get unit test tool such to Karma to do the test. In order to start E2E test, we should get unit test pass first ; most of time the E2E test doesn't pass is not because something make different when everything is combining together , but the  logic of the individual controllers, directives, and services is working incorrect.
       -  For ex: I have a test running that opening a modal but one of the function,launchSignUp, doesn't exist or the var inside the function has been change. This will cause the E2E failed, but however it is not "weird" bugs but just the mistake from function
  ```
## Task 1: Long workflow for iOS without any bugs
- [x] Propose how long it will take & what you will have accomplished every 1 hour (worst case times). Make this list right underneath this checkbox
  - [x] [10 mins] set up the new  config for IOS test 
         - First time running E2E -> xcode build -> instruments -> start E2E 
  - [x] [45 mins] to an hour to figure out why school doesn't get select.
        - ios can't clikc <li> but <a>  
  -  [x] [30mins] Long work flow for Test random access code -> Sekect a university->Welcome uguru logo pop-> Opening FAQ & Support Modal and closed ->Become Guru Process -> Sign up -> Guru Profile -> Check all Creditability Page
    - IOS won't have any action when li is click in this case we will need to click at <a>
  - [x] [15 mins] Check Switch alert dialog work
  ##### Known Issue on IOS
  - [ ] [45 mins] Understand why browser.manage().logs() doesn't work
  - [ ] browser.action doesn't work.
  - [ ] li is not click able in IOS and safari
  - [ ] [ 30 mins] Understand why skill under subcategory is not able to select and get freezed
  - [x] 5PM 
- [x] Message Samir to look at this 
- [ ] Get started! 
## Task 2: Web-page (not desktop) debug
- [ ] Create a list of all platforms && sizes that you will need to run these tests for. Each platform has MANY sizes and could have MANY versions. Only describe ones that are used by more than 2-3% of the entire population. 
  - basic from http://www.w3schools.com/browsers/browsers_display.asp we have :
  - From Highest rate to lowest rates 
    - '1920x1080','1366x768','1280x1024','1280x800' ,'1024x768', '1440x900', '1600x900', '1680x1050',      '1920x1200', '1360x768'
- [ ] Make a list of all the bugs && how you would test it using FIRST principles. Do not write any code yet. This list should be
  - concise
  - effective, it's basically pseudo code -- programming it will be easy because you are just focusing on the syntax.
