### ISSUE TITLE
Overall Keyboard Issues

### ISSUE THREAD

**Issue by sam1rm** [u-guru/uguru#409]
- [ ] Android keyboard doesn't pop as expected, referenced previously #372
- [ ] Windows keyboard doesn't pop as expected, referenced previously #366
- [x] Keyboard pop up randomly at onborading, referenced previously #363

@f230536 ^^ This is a great example of how I generalized three bugs into one, and immediately reference & close them
